Repository andrewvallejo/only-devs, pull requests merged in 2021-07, with the labels that each got.

#5 Add Component folder and components with respective files
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Question/Question.css
  src/Components/Question/Question.js
  src/Components/QuestionBoard/QuestionBoard.css
  src/Components/QuestionBoard/QuestionBoard.js
Labels: feature, setup

#23 Refactor/question
  src/Components/Answer.js
  src/Components/App.js
  src/Components/Card.js
  src/Components/Header.js
  src/Components/Question.js
  src/Components/QuestionBoard.js
  src/Components/QuestionDetails.js
  src/styles/V-components/Answer.scss
  src/styles/V-components/Question.scss
  src/styles/styles.scss
Labels: component, refactor

#27 Add live-search bar
  src/Components/QuestionBoard.js
Labels: feature, refactor
